Fix style issues on dashboard page
jellyfin/jellyfin-web pull request #2218
Opened 2020-12-10 15:51 UTC by thornbill

**Changes**
* Adjusts the column layout on the dashboard page to avoid tiny columns on small screens
* Adds a min-width to the session cards to avoid tiny cards on small screens
* Adds top/bottom margins for stacked emby-buttons

**Before:**
![Screenshot_2020-12-10 Jellyfin](https://user-images.githubusercontent.com/3450688/101794973-6c0a6e00-3ad5-11eb-97d4-87508356c11c.png)

**After:**
![Screenshot_2020-12-10 Jellyfin(1)](https://user-images.githubusercontent.com/3450688/101795032-775d9980-3ad5-11eb-9648-21e5f40229af.png)

**Issues**
Fixes: #2088

2020-12-10 17:23 UTC, nyanmisaka commented
Tried on 3840x2160 225% screen.
<img src="https://user-images.githubusercontent.com/14953024/101806654-31451c00-3b4f-11eb-9638-d9841bc6b03f.png" width = "1920" align=center />

2020-12-11 05:32 UTC, dkanada submitted a review, later dismissed

2020-12-11 15:59 UTC, thornbill commented
I doubt I will be able to reproduce the issue above because it’s probably specific to the resolution and pixel ratio. Increasing the min-width would probably fix it. I experimented with values from 10-15 rem. Maybe 12 would work?

2020-12-11 18:49 UTC, nyanmisaka commented
Change to 14rem seems to be fine on edge. But session cards on iPad are too big than before.
Can we just reduce the font and icon size in session cards to avoid this issue?

Before this PR:
![IMG_0457](https://user-images.githubusercontent.com/14953024/101941404-e4327a00-3c22-11eb-932d-a84b11e91d95.jpg)
After:
![IMG_0456](https://user-images.githubusercontent.com/14953024/101941397-e1d02000-3c22-11eb-8b27-2fbca2a6ceb7.jpg)

2020-12-12 16:37 UTC, thornbill commented
This still needs some tweaking as gap has poor browser support.

2020-12-14 15:14 UTC, thornbill commented
This should be good for review now.

2020-12-16 06:46 UTC, nyanmisaka commented
The card will still be enlarged when the sessions is more than 2.
Can we set a maximum width for the card? 
Everything else is fine.

2020-12-16 16:27 UTC, thornbill commented
@nyanmisaka I'm not seeing that now, could you grab a screenshot of that? Thanks!

2020-12-16 16:42 UTC, nyanmisaka commented
> @nyanmisaka I'm not seeing that now, could you grab a screenshot of that? Thanks!

https://github.com/jellyfin/jellyfin-web/pull/2218#issuecomment-743362824
The latter is very empty when it is not playing. And it occupies almost the entire page. It would be fine if it were the former.

2020-12-16 19:38 UTC, ferferga approved these changes

2020-12-16 21:39 UTC, thornbill commented
@nyanmisaka would you care to check how this looks now? I don't think they seem _too_ large now, but I can still tweak it if needed!

2020-12-18 15:15 UTC, nyanmisaka approved these changes
It looks good for me.

2020-12-19 08:48 UTC, nyanmisaka requested changes

2020-12-19 08:48 UTC, nyanmisaka commented on src/assets/css/dashboard.css
> +    min-width: 15rem;
```suggestion
    min-width: 20rem;
```

2020-12-19 08:48 UTC, nyanmisaka commented on src/assets/css/dashboard.css
> +    min-width: 15rem;
15rem is still a bit narrow on iPad safari.

15rem<img src="https://user-images.githubusercontent.com/14953024/102685124-2c502e80-4219-11eb-8bbb-f7f08c79ff33.jpg" width = "200" align=center />
20rem<img src="https://user-images.githubusercontent.com/14953024/102685129-2fe3b580-4219-11eb-9afe-19a50f4e8b2b.jpg" width = "200" align=center />

2020-12-23 03:24 UTC, joshuaboniface approved these changes

2020-12-23 03:24 UTC, merged