Edit admin dashboard menu for plugins
jellyfin/jellyfin-web pull request #2327
Opened 2021-01-12 03:39 UTC by MrChip53

**Changes**
I think it would look a little more tidy in the menu if un sorted plugin menu items were under their own section. Also, would like to be able to add plugin items under Live TV(Maybe should allow this for all sections?).

Uhh sorry if its trash code and if you all don't want it thats A-OK 😅

Also, TBH.... I don't know how to test jellyfin-web sorry

**Issues**

2021-01-12 04:28 UTC, MrChip53 commented
No Plugins:

![Screenshot (2)](https://user-images.githubusercontent.com/57076668/104269433-e70bcf00-545b-11eb-8e0d-b0a5e8aab3f2.png)

With unsorted and live tv plugins:

![Screenshot (3)](https://user-images.githubusercontent.com/57076668/104269562-35b96900-545c-11eb-9f2f-57c338ff9e5d.png)

2021-01-21 18:29 UTC, nielsvanvelzen requested changes

2021-01-21 18:29 UTC, nielsvanvelzen commented on src/scripts/libraryMenu.js
> +        for (let i = 0, length = pluginItems.length; i < length; i++) {
I think you can do `for (const pluginItem of pluginItems) {` here

2021-01-22 21:02 UTC, MrTimscampi commented
Some thoughts about UX, which may or may not be valid:

Currently all the config pages are in one place only. It's easy to find them since they all end up in the same place.

Allowing plugins to add themselves to the menu leads to worse UX, imo, since now plugins can end up wherever (I know the feature is already there, but nothing really used it until now).

Furthermore, with the expected plans for the v2 API, plugin pages will be auto-generated from JSON, meaning they'll essentially only be a simple form for configuration. This reduces the utility of this quite a bit, imo.

2021-01-22 22:51 UTC, MrChip53 commented
> Furthermore, with the expected plans for the v2 API, plugin pages will be auto-generated from JSON, meaning they'll essentially only be a simple form for configuration. This reduces the utility of this quite a bit, imo.

This seems like a major regression and severely limits the capabilities of plugins. Can this be an optional feature just used to maybe lower the bar of entry for creating a plugin?

2021-01-23 10:16 UTC, MrTimscampi commented
> Can this be an optional feature just used to maybe lower the bar of entry for creating a plugin?

The current way plugin pages work is pretty dirty and unsafe (We're taking HTML wholesale, parsing it all and inserting it into the DOM), and relies pretty much entirely on jellyfin-web polluting `window` to have access to anything.

The idea is to remove the dependency on web. Ultimately, we want the web client to be "just another client". Currently, the server is heavily tied to it and that's an issue.

2021-01-25 07:47 UTC, nielsvanvelzen approved these changes

2021-01-26 18:01 UTC, thornbill approved these changes

2021-01-26 18:06 UTC, thornbill commented
I don't see any reason to block this right now. It's a marginal improvement to how plugins currently work. When we start planning for a new plugin configuration schema we can decide what features should (or should not) be included.

2021-01-26 18:07 UTC, merged