KnownProxies now supports hostnames too
jellyfin/jellyfin-web pull request #2497
Opened 2021-03-09 15:42 UTC by PrplHaz4

Per https://github.com/jellyfin/jellyfin/pull/4675 hostnames are supported in the KnownProxies field.

2021-03-09 17:02 UTC, ThibaultNocchi requested changes

2021-03-09 17:02 UTC, ThibaultNocchi commented on src/strings/en-gb.json
> +    "KnownProxiesHelp": "Comma separated list of IP addresses/hostnames of known proxies used when connecting to your Jellyfin instance. This is required to make proper use of X-Forwarded-For headers
Please only edit the master file (ie. `en-us`) on commits, then use Weblate for the others :)

2021-03-09 22:38 UTC, ThibaultNocchi approved these changes

2021-03-12 06:08 UTC, dkanada commented on src/strings/en-us.json
> +    "KnownProxiesHelp": "Comma separated list of IP addresses/hostnames of known proxies used when connecting to your Jellyfin instance. This is required to make proper use of X-Forwarded-For headers
```suggestion
    "KnownProxiesHelp": "Comma separated list of IP addresses or hostnames of known proxies used when connecting to your Jellyfin instance. This is required to make proper use of X-Forwarded-For headers. Requires a reboot after saving.",
```

2021-03-12 15:35 UTC, ThibaultNocchi commented
Could you squash your 4 commits please? :)

2021-03-22 18:11 UTC, dkanada approved these changes

2021-03-22 18:11 UTC, merged