Disable first episodes in Next Up home section
jellyfin/jellyfin-web pull request #2509
Opened 2021-03-14 04:33 UTC by MrTimscampi

**Changes**
This makes use of the new API parameter to remove the first episodes which show up by default when the user hasn't watched anything yet.

Pretty much all the streaming services behave this way, and so do other media servers.

**Issues**

2021-03-14 04:34 UTC, MrTimscampi commented
Marked it as a stable backport since it's a one-liner and I tested it against a 10.7.0 server. Feel free to remove if it's not something we'd want to backport.

2021-03-14 07:01 UTC, cvium commented
If it's not configurable, I don't see why it should be backported tbh

2021-03-14 13:51 UTC, MrTimscampi commented
> If it's not configurable, I don't see why it should be backported tbh

Because it's technically a bug. It was fixed during 10.7 but had to be reversed (and this parameter added) because Android TV relied on the weird implementation of that endpoint for some things.

We've had a few issues opened for it before, so imo it would warrant a fix.

Essentially, we're the only weird ones that do "Next up" like this. It's not a suggestions section, it's supposed to list things you're currently watching and may want another episode of. The behavior is also likely inconsistent (as mentioned in #2430) and I don't think holding a 1-line fix for 6+ months is the right call.

2021-03-15 13:54 UTC, thornbill commented
Related server PRs for context:
https://github.com/jellyfin/jellyfin/pull/4595
https://github.com/jellyfin/jellyfin/pull/5027

2021-03-18 04:11 UTC, thornbill commented
This does constitute a behavioral change which strictly speaking should have been in before the final 10.7 release especially given the extended release candidate cycle this time around. I'm also not convinced that this is really a bug. It was probably intended to provide additional content on the home screen for the initial user experience.

Code wise it is a very minor change and there is at least the one issue you linked for it, so maybe it is fine to backport without causing backlash. :man_shrugging:

2021-03-19 16:14 UTC, dkanada approved these changes

2021-03-19 17:23 UTC, thornbill requested changes
Any relevant issues should be linked in the description so they get tracked properly.

2021-03-21 16:20 UTC, joshuaboniface commented
I'm not opposed to backporting it, but I'd be concerned if people *liked* this setup. But that said, I think it's obscure enough, and if there's been several issues mentioning it like a bug, I'd say let's just go for it.

2021-04-09 19:18 UTC, thornbill approved these changes

2021-04-09 19:19 UTC, merged

2022-12-26 13:59 UTC, TimGels commented
I had a discussion with some people over at Discord about this and it seems to be happening again with 10.8.8. I created a new user to try and reproduce this (this user hasn't watched anything yet). Result, it seems to be happening.
![afbeelding](https://user-images.githubusercontent.com/43609220/209556096-fe09965a-a2a0-4b52-a7dd-2ea2dd682169.png)