Plugins and Changes for Jellyfin Media Player
jellyfin/jellyfin-web pull request #2557
Opened 2021-04-07 05:58 UTC by iwalton3

This allows the stock jellyfin-web to work as a web client in Jellyfin Media Player.

**Changes**
 - Add player property `useServerPlaybackInfoForAudio` that forces server-side media decisions for music.
 - Add player property `useFullSubtitleUrls` that resolves relative external subtitles URLs into full URLs for MPV.
 - Add support to SyncPlay for `currentTimeAsync` method required to get accurate time from MPV.
 - Add `ignorePlayPermission` to the `config.json` to allow skipping audio permission checks.
 - Update the mouse movement checkers to also use `clientX`/`clientY` as QtWebEngine returns zeros otherwise.
 - Add player property `mustDestroy` which forces a `.stop()` call on the player before navigating away.
 - Add MPV player plugins `mpvAudioPlayer` and `mpvVideoPlayer` which are not enabled by default.

To use the client with JellyfinMediaPlayer, set these options in `config.json`:

```diff
@@ -1,7 +1,7 @@
 {
   "includeCorsCredentials": false,
-  "multiserver": false,
-  "ignorePlayPermission": false,
+  "multiserver": true,
+  "ignorePlayPermission": true,
   "themes": [
     {
       "name": "Apple TV",
@@ -28,8 +28,8 @@
   "plugins": [
     "playAccessValidation/plugin",
     "experimentalWarnings/plugin",
-    "htmlAudioPlayer/plugin",
-    "htmlVideoPlayer/plugin",
+    "mpvAudioPlayer/plugin",
+    "mpvVideoPlayer/plugin",
     "photoPlayer/plugin",
```

2021-05-04 17:45 UTC, thornbill commented on src/components/apphost.js
> +        if (window.NativeShell && window.NativeShell.AppHost.exit) {
I would suggest using optional chaining for this type of checks.

```suggestion
        if (window.NativeShell?.AppHost?.exit) {
```

2021-06-24 05:48 UTC, thornbill requested changes
Looks good! Just a couple minor notes.

2021-06-24 05:48 UTC, thornbill commented on src/components/syncPlay/ui/playbackPermissionManager.js
> +    async check () {
async/await doesn't seem necessary here. I think you could just return `Promise.resolve(true)` below and remove the await when returning the promise.

2021-06-24 05:48 UTC, thornbill commented on src/components/upnextdialog/upnextdialog.js
> +        const e = await new Promise((resolve) => {
A more descriptive variable name might be good here instead of "e".

2021-06-30 18:47 UTC, thornbill approved these changes
:+1: lgtm. Have you tested this with any of the other wrapper apps?

2021-06-30 21:19 UTC, iwalton3 commented
I have tested with JMP and the web app only.

2021-07-10 04:51 UTC, merged