Add TypeScript support for React components
jellyfin/jellyfin-web pull request #2722
Opened 2021-06-11 12:57 UTC by MrTimscampi

**Changes**

Adds TypeScript support and converts the few React components to TSX.

Compared to #2404, it doesn't add the typed API client, but defines `window.ApiClient` as any.

Some issues remain in the current state, due to how the files are currently structured: ESLint throws warnings for the `useEffect` hook whenever there is no dependency array but the hook uses something external. However, in some cases, filling this leads to further warning about the dependencies making the hook change on every render.

**Issues**
Supercedes #2404

2021-06-14 18:12 UTC, thornbill requested changes
I'm new to TypeScript, but it looks like the type definitions you added for props should completely replace the `PropTypes` used previously.

2021-06-15 02:45 UTC, MrTimscampi commented
> I'm new to TypeScript, but it looks like the type definitions you added for props should completely replace the `PropTypes` used previously.

From what I looked at, PropTypes is at runtime, while TypeScript is at build time. They serve different purposes.

Of course, we could remove PropTypes, but then, we'd lose runtime validation for prop types. Do we want that?

2021-06-15 03:15 UTC, thornbill commented
In the docs it sounds like it's not needed if you use Typescript or Flow. https://reactjs.org/docs/typechecking-with-proptypes.html

2021-06-15 10:08 UTC, MrTimscampi commented
Fair enough :)

I removed the `prop-types` package and adjusted things a bit to please the linter in regards to prop validation.

2021-06-15 14:15 UTC, thornbill commented on src/components/pages/SearchPage.tsx
> +    serverId: string,
Should we use `?:` here since these are optional?

2021-06-21 13:52 UTC, thornbill approved these changes

2021-06-21 13:52 UTC, merged