Update apiclient
jellyfin/jellyfin-web pull request #3001
Opened 2021-09-24 03:35 UTC by thornbill

**Changes**
Bumps the apiclient to the latest release

**Issues**
Fixes #2909

2021-09-24 19:49 UTC, dmitrylyzo approved these changes

2021-09-25 11:31 UTC, dmitrylyzo requested changes
Now I'm thinking, _What was I testing then?_ :sweat_smile: 
Because of [this](https://github.com/jellyfin/jellyfin-apiclient-javascript/blob/18cc70b52fca88ddea2d915d445a7bd5bc1a4167/babel.config.js#L5) babel doesn't use specified targets in the browserlist - there is `let` in the `dist`.

2021-09-27 04:31 UTC, thornbill commented
We should fix the apiclient and publish a new version imho. I opened a PR to fix it here: https://github.com/jellyfin/jellyfin-apiclient-javascript/pull/304.

2021-09-29 14:47 UTC, dmitrylyzo approved these changes

2021-09-29 17:46 UTC, merged