Add "Select All" action to multiSelect
jellyfin/jellyfin-web pull request #3296
Opened 2022-01-05 10:43 UTC by marius-luca-87

**Changes**

Adds a "Select all" helper to the multi-select menu.

![image](https://user-images.githubusercontent.com/7069165/148204413-549dbd99-cb40-42ee-a985-dba014fdb8f7.png)

2022-01-05 11:01 UTC, ferferga approved these changes

2022-01-05 15:14 UTC, thornbill requested changes

2022-01-05 15:14 UTC, thornbill commented on src/components/multiSelect/multiSelect.js
> +                                                if (!chkItemSelect.classList.contains('checkedInitial') && !chkItemSelect.checked) {
I would combine these two if statements.

2022-01-06 19:03 UTC, thornbill commented
I noticed an unusual behavior when testing this. In this screen there should be 100 items shown and selected, but for some reason there appears to be 226 selected.

![all selelcted](https://user-images.githubusercontent.com/3450688/148436856-471155d0-5776-4b05-94d5-71d7de5eeb9b.png)

2022-01-06 22:02 UTC, marius-luca-87 commented
Apparently a few cards are left hidden and the way the current system works is by assuming you will never be able to click them.
![image](https://user-images.githubusercontent.com/7069165/148458056-b3ae09dc-8387-4fab-8e66-71fc530e75e1.png)
The only quick way I could find would be to check for "chkItemSelect.getBoundingClientRect().width != 0" before selecting them.

2022-01-07 16:13 UTC, thornbill approved these changes
Well that is not great... it definitely shouldn't be enabling the multiselect stuff on hidden pages or inactive tabs, but that doesn't relate to your changes really. I think your work around for that is fine. I will see if I can find a fix to prevent multiselect from being enabled on the hidden views after this is merged. :sweat_smile:

2022-01-07 16:13 UTC, merged