Provide more friendly transcoding bitrate options.
jellyfin/jellyfin-web pull request #3506
Opened 2022-03-20 13:08 UTC by shenwii

Changed the bitrate option for transcoding.
*Remove some high bitrate options, such as 1080P 60M
*Add some low bitrate options, for example, for 1080P, there should be lower bitrate options, such as 4M, setting 10M as the lowest bitrate for 1080P is not appropriate, in fact, most 1080P bitrates are less than 10M

Filter out transcoding options that are higher than the source streaming bitrate multiplied by 3.
For example, a 1080P 10M hevc source transcoded to 1080P 40M does not make much sense.

PS: I know that hardware-accelerated transcoding is worse than CPU transcoding, and HEVC encoding has better compression, but even so, the transcoded bitrate is not more than 3 times the original bitrate at about the same image quality, I think.

2022-11-30 08:58 UTC, Shadowghost commented
Just as a sidenote: AFAIK currently the resolution isn'tt aken into account at all by the transcoder, only bitrate and display resolution.

2024-05-18 01:39 UTC, 1hitsong requested changes

2024-05-18 01:39 UTC, 1hitsong commented on src/components/qualityOptions.js
> +                if (qualityOption.bitrate < videoBitRate * maxStreamingBitrateMultiplier) {
By running the `videoBitRate * maxStreamingBitrateMultiplier` calculation in all these forEach functions you're calculating the same value 24 times. Better to move it outside of these loops and only calculate it once.

2024-05-18 01:42 UTC, 1hitsong commented
Functionally, it works well. Just some minor code cleanup / optimization items to address.

2024-09-20 19:03 UTC, thornbill commented
Superseded by #6071

2024-09-20 19:03 UTC, closed without merging