Add option to allow extras to use embedded titles
jellyfin/jellyfin-web pull request #3652
Opened 2022-05-17 21:10 UTC by 1337joe

I took the time to embed titles in my extras (including characters not valid for use in filenames) and was annoyed when Jellyfin ignored the embedded value. Finally got around to adding an option to enable it.

**Changes**
- Add a sub-option for `EnableEmbeddedTitles` to also `EnableEmbeddedExtrasTitles`

**Issues**
- Implements UI side of jellyfin/jellyfin#7767

2023-02-07 16:57 UTC, thornbill requested changes
I think I got the logic right in my suggestions, but I haven't checked it. :sweat_smile:

2023-02-07 16:57 UTC, thornbill commented on src/components/libraryoptionseditor/libraryoptionseditor.js
> +        });
```suggestion
        parent.querySelector('#chkEnableEmbeddedTitles').addEventListener('change', (e) => {
            parent.querySelector('.chkEnableEmbeddedExtrasTitlesContainer').classList.toggle('hide', !e.currentTarget.checked);
        });
```

2023-02-07 16:57 UTC, thornbill commented on src/components/libraryoptionseditor/libraryoptionseditor.js
> +        }
```suggestion
    parent.querySelector('.chkEnableEmbeddedExtrasTitlesContainer').classList.toggle('hide', !options.EnableEmbeddedTitles);
```

2023-02-11 03:35 UTC, 1337joe commented
> I think I got the logic right in my suggestions, but I haven't checked it. sweat_smile

I just tested your suggested changes and it worked exactly as expected

2023-02-11 16:30 UTC, 1337joe commented on src/components/libraryoptionseditor/libraryoptionseditor.js
> +    parent.querySelector('.chkEnableEmbeddedExtrasTitlesContainer').classList.toggle('hide', !options.EnableEmbeddedTitles);
Was definitely off, I didn't look at that at all when I applied your suggestions.

2023-02-12 00:11 UTC, thornbill approved these changes

2023-02-12 00:11 UTC, merged