Recognize MIME for transcoded audio in streams
jellyfin/jellyfin-web pull request #3716
Opened 2022-06-16 19:41 UTC by Orhideous

After jellyfin/jellyfin#6941 MIME library returns IETF-approved type (`application/vnd.apple.mpegurl`) instead of old one (`application/x-mpegURL`), but latter was hardcoded in player plugin.

**Changes**
Use correct MIME-type for transcoded streams.

**Issues**
Fixes: #3663

2022-06-16 19:47 UTC, crobibero commented
I'm no authority on the web client but I would probably allow either to be specified

2022-06-16 21:10 UTC, thornbill commented
I agree with @crobibero's comment above. Let's keep both for now just in case someone is connecting to a 10.7 server or some other unusual case is hit here.

2022-06-17 10:33 UTC, nyanmisaka requested changes

2022-06-17 10:33 UTC, nyanmisaka commented on src/plugins/htmlAudioPlayer/plugin.js
> +                if (contentType === 'application/vnd.apple.mpegurl') {
```suggestion
                if (contentType === 'application/vnd.apple.mpegurl' || contentType === 'application/x-mpegurl') {
```

2022-06-17 10:47 UTC, nyanmisaka approved these changes

2022-06-17 11:48 UTC, crobibero approved these changes

2022-06-17 14:05 UTC, thornbill approved these changes

2022-06-17 14:05 UTC, merged