Add eslint no-shadow rule and fix violations
jellyfin/jellyfin-web pull request #4058
Opened 2022-10-16 14:15 UTC by Aimekram

**Changes**
- Enable no-shadow rule in eslint, use one from @typescript-eslint, so it doesn't show errors on enums
- Fix all shadowed variable names

**Issues**
- Fixes https://github.com/jellyfin/jellyfin-web/issues/3494 no-shadow case

2022-10-18 20:35 UTC, thornbill requested changes
This is looking great! I just handful of nitpicky comments. :sweat_smile:

2022-10-18 20:35 UTC, thornbill commented on src/components/maintabsmanager.js
> +              currentElement.selectNext();
Indentation looks off here and in the next change in this file.

2022-10-18 20:35 UTC, thornbill commented on src/elements/emby-textarea/emby-textarea.js
> +    function calculateOffset(textarea) {
Since this is being moved, it should go above the eslint comment above so its indentation can be checked.

2022-10-18 20:35 UTC, thornbill commented on src/controllers/music/musicrecommended.js
> +                setScrollClasses(containers[i], enableScrollXmobile());
We could probably just remove this function and use the `browser.mobile` value directly.

2022-10-18 20:35 UTC, thornbill commented on src/controllers/shows/episodes.js
> +          tabElement.querySelector('.btnFilter').addEventListener('click', function () {
Indentation looks off.

2022-10-18 20:35 UTC, thornbill commented on src/controllers/movies/moviecollections.js
> +          tabElement.querySelector('.btnSort').addEventListener('click', function (e) {
Indentation looks off.

2022-10-18 20:35 UTC, thornbill commented on src/plugins/htmlVideoPlayer/plugin.js
> +                        const newdlg = document.createElement('div');
Maybe `playerDlg` would be a better name here?

2022-10-18 20:35 UTC, thornbill commented on src/plugins/htmlVideoPlayer/plugin.js
> +                          newdlg.classList.add('videoPlayerContainer-onTop');
Indentation

2022-10-18 20:35 UTC, thornbill commented on src/plugins/youtubePlayer/plugin.js
> +                const newdlg = document.createElement('div');
Maybe `playerDlg` would be a better name here?

2022-10-18 20:35 UTC, thornbill commented on src/components/shortcuts.js
> +            const myServerId = apiClient.serverInfo().Id;
Maybe name this `currentServerId`?

2022-10-19 20:25 UTC, Aimekram commented
Hi @thornbill, thanks for the CR! I made the suggested changes :)

2022-10-20 14:54 UTC, thornbill approved these changes

2022-10-20 14:56 UTC, merged