Convert emby-button and emby-scroller to react
jellyfin/jellyfin-web pull request #4173
Opened 2022-11-16 18:53 UTC by grafixeyehero

2022-12-08 19:05 UTC, thornbill requested changes
Sorry for the delay, I've been working on some other random things and just got back around to doing some reviews here. :sweat_smile: 

Looks great overall, I just had a few minor suggestions!

2022-12-08 19:05 UTC, thornbill commented on src/elements/emby-scroller/Scroller.tsx
> +                    /> : null
```suggestion
                showControls && scrollState.scrollWidth > scrollState.scrollSize + 20 &&
                    <ScrollButtons
                        scrollRef={scrollRef}
                        scrollerFactoryRef={scrollerFactoryRef}
                        scrollState={scrollState}
                    />
```

2022-12-15 21:31 UTC, grafixeyehero commented on src/elements/emby-button/Button.tsx
> +            {icon && iconPos === 'LEFT' && <span className={classNames('material-icons', iconClassName, icon)} aria-hidden='true'></span>}
https://github.com/jellyfin/jellyfin-web/pull/4173/commits/72cbd3718206ceb15c0c2b68e53039ff2fc466db

2022-12-16 19:12 UTC, thornbill approved these changes

2022-12-16 19:12 UTC, merged