Add eslint max-params rule with a max of 7 parameters
jellyfin/jellyfin-web pull request #4320
Opened 2023-02-01 04:18 UTC by pl-ducharme

**Changes**

- Add eslint max-params rule with a max of 7 parameters
- Refactor code where there was more than 7 parameters

**Issues**

Fixes #3494 max-params case

2023-02-07 18:13 UTC, thornbill commented on src/components/cardbuilder/cardBuilder.js
> +                innerCardFooter += getCardFooterText(item, apiClient, options, footerCssClass, progressHtml, {forceName: forceName, overlayText: overlayText, isOuterFooter: false}, {imgUrl: imgUrl, l
There are several places in these changes where you could simplify things by using the object shorthand syntax.

```suggestion
                innerCardFooter += getCardFooterText(item, apiClient, options, footerCssClass, progressHtml, { forceName, overlayText, isOuterFooter: false }, { imgUrl, logoUrl });
```

2023-03-07 14:35 UTC, thornbill requested changes
Hey @pl-ducharme would you be able to fix the merge conflicts on this? Thanks!

2023-03-08 04:40 UTC, pl-ducharme commented
> Hey @pl-ducharme would you be able to fix the merge conflicts on this? Thanks!

Sure @thornbill! Should be good now

2023-03-09 03:57 UTC, thornbill approved these changes

2023-03-09 03:57 UTC, merged