Show clock in TV layout
jellyfin/jellyfin-web pull request #4441
Opened 2023-03-22 17:36 UTC by addamanth

Show clock in TV layout

**Changes**
Show clock in TV layout in header

2023-03-30 14:26 UTC, thornbill commented
It would be nice to include a screenshot in the PR description for a UI change like this. :slightly_smiling_face:

2023-04-07 16:41 UTC, addamanth commented
> It would be nice to include a screenshot in the PR description for a UI change like this. 🙂

Screenshots attached

2023-04-17 17:15 UTC, thornbill requested changes
Looks great! Just one minor suggestion.

2023-04-18 07:46 UTC, addamanth commented on src/scripts/libraryMenu.js
> +                 currentTimeText.innerHTML = datetime.getDisplayTime(new Date());
Thank you for the feedback!
PR updated with the suggested change

2023-04-18 13:23 UTC, merged

2024-01-06 00:06 UTC, DrConflict commented
Could the clock also be added to the screensaver by any chance? Really looking forward to having this feature added in 10.9!