fix: dead link
jellyfin/jellyfin-web pull request #4485
Opened 2023-04-10 18:24 UTC by brettpetch

**Changes**

**Issues**

2023-04-10 18:48 UTC, nielsvanvelzen commented
We might want to add a page to our own documentation at jellyfin.org that links to these kinds of resources, that way we won't have broken links in existing releases.

2023-04-10 19:21 UTC, nyanmisaka commented
Better to link it to https://jellyfin.org/docs/general/administration/hardware-acceleration/intel#configure-and-verify-lp-mode-on-linux

2023-04-12 03:45 UTC, thornbill requested changes

2023-04-12 03:45 UTC, thornbill commented on src/controllers/dashboard/encodingsettings.html
> +                                <a is="emby-linkbutton" rel="noopener noreferrer" class="button-link" href="https://01.org/group/43/downloads/firmware" target="_blank">${IntelLowPowerEncHelp}</a>
```suggestion
                                <a is="emby-linkbutton" rel="noopener noreferrer" class="button-link" href="https://jellyfin.org/docs/general/administration/hardware-acceleration/intel#configure-and-verify-lp-mode-on-linux" target="_blank">${IntelLowPowerEncHelp}</a>
```

2023-04-12 14:06 UTC, thornbill approved these changes

2023-04-12 14:06 UTC, merged