Add "AllowedTags" option to parental controls (updated)
jellyfin/jellyfin-web pull request #4535
Opened 2023-04-25 02:27 UTC by davidangel

(copied from https://github.com/jellyfin/jellyfin-web/pull/4338 - updates to frontend + merge conflict resolution)

Changes
Adds an option in Parental Controls to only allow media with selected tags for viewing.

Issues
Client side configuration of https://github.com/jellyfin/jellyfin/pull/9139

2023-06-24 12:58 UTC, adoreparler commented
@davidangel  you still working on this? Has the server side been updated?

2023-06-24 14:19 UTC, Shadowghost commented
Server functionality was already merged into master

2023-06-24 18:29 UTC, adoreparler commented
Sorry new to this project. How do we get it through the SonarCloud check?

2023-06-26 01:46 UTC, adoreparler commented
Testing this out and it does not seem to be working. I added a tag to the allowed tags section for another user. Logged in as that user and they still see everything. I will keep testing and look at the code

2023-06-27 15:25 UTC, adoreparler commented
Seeing everything was a cached thing, I refreshed and it disappeared. But its still not working, I add a tag to a video and to the allowed tags for another user and log in with them and refresh and nothing shows. Will keep playing around

2023-06-27 15:35 UTC, xangelix commented
I have not tested this PR but suspect it is operating on the same logic here https://github.com/jellyfin/jellyfin-web/pull/4338#issuecomment-1483906272
You have to also add the allowed tag to each containing layer, such as the library itself.

2023-07-15 13:38 UTC, davidangel commented
Updated this. I'm testing against my own "prod" backend, so `AllowedTags` doesn't seem to be populating, but I think this should be working when the backend provides this data.

2023-07-15 14:35 UTC, adoreparler commented
I'll try and pull a fresh copy of the back end and this PR later tonight and test. 

It was not working when I tested it previously. I was testing this at a per item basis, so add a new tag like "kids" to a user allowed tags, and then add that tag to a bunch of videos and then login as that user and those videos tagged with kids should only show up for that user.

2023-09-23 15:38 UTC, Siress commented
Thank you for working on this!

2023-11-30 05:43 UTC, thornbill requested changes

2023-11-30 05:43 UTC, thornbill commented on src/apps/dashboard/routes/users/parentalcontrol.tsx
> +            }).catch(err => {
This `catch` would never get called right? Since the dynamic `import` has been removed, it can probably just be removed.

2023-11-30 05:43 UTC, thornbill commented on src/apps/dashboard/routes/users/parentalcontrol.tsx
>              }).catch(err => {
Same thing here.

2023-11-30 05:43 UTC, thornbill commented on src/strings/en-gb.json
> +    "LabelAllowedRemoteAddresses": "Remote IP address filter:",
Only the `en-us` language should be updated in PRs otherwise it can cause conflicts with weblate (translate.jellyfin.org).

2023-12-30 13:36 UTC, girishso commented
Not working, I get an empty media library.  I add a tag to a video and to the allowed tags for another user and log in with them and refresh and nothing shows.

2024-03-25 07:36 UTC, thornbill approved these changes
These frontend changes seem to work as expected, although it did expose a bug with the server behavior.

2024-03-25 07:37 UTC, merged