Add Filter,  short and view setting components
jellyfin/jellyfin-web pull request #4711
Opened 2023-07-08 16:29 UTC by grafixeyehero

2023-07-11 21:00 UTC, thornbill requested changes

2023-07-12 16:14 UTC, grafixeyehero commented on src/apps/experimental/components/library/filter/FiltersYears.tsx
> +    filtes?: QueryFiltersLegacy;
https://github.com/jellyfin/jellyfin-web/pull/4711/commits/9cd330ef1580063b03c265b585433be45a948c9c

2023-07-12 16:15 UTC, grafixeyehero commented on src/apps/experimental/components/library/filter/FiltersTags.tsx
> +    filtes?: QueryFiltersLegacy;
https://github.com/jellyfin/jellyfin-web/pull/4711/commits/9cd330ef1580063b03c265b585433be45a948c9c

2023-07-12 16:15 UTC, grafixeyehero commented on src/apps/experimental/components/library/filter/FiltersGenres.tsx
> +    filtes?: QueryFiltersLegacy;
https://github.com/jellyfin/jellyfin-web/pull/4711/commits/9cd330ef1580063b03c265b585433be45a948c9c

2023-07-12 16:15 UTC, grafixeyehero commented on src/apps/experimental/components/library/filter/FiltersStudios.tsx
> +    filtes?: BaseItemDtoQueryResult;
https://github.com/jellyfin/jellyfin-web/pull/4711/commits/9cd330ef1580063b03c265b585433be45a948c9c

2023-07-12 16:16 UTC, grafixeyehero commented on src/hooks/useFetchItems.ts
> +    parentId: string | null | undefined,
https://github.com/jellyfin/jellyfin-web/pull/4711/commits/e9fb141431ab095c85da34669e0ee159eeb233a4

2023-07-14 14:49 UTC, thornbill approved these changes

2023-07-14 14:49 UTC, merged