Migrate dashboard to separate app
jellyfin/jellyfin-web pull request #4816
Opened 2023-09-30 05:39 UTC by thornbill

**Changes**
* Moves the dashboard and metadata editor to a separate app using mui navigation components
* Update dashboard paths to simplify routing
* Removes the old version of the activity log page

**Issues**
N/A

2023-09-30 06:15 UTC, thornbill commented on src/components/dashboard/users/SectionTabs.tsx
>          class="${activeTab === 'useredit' ? 'ui-btn-active' : ''}"
This file can probably be removed since tabs are no longer used in the dashboard navigation

2023-10-02 20:26 UTC, grafixeyehero requested changes

2023-10-03 17:17 UTC, thornbill commented on src/apps/dashboard/routes/_asyncRoutes.ts
> +    { path: 'users/new' },
whoops nice catch!

2023-10-03 21:47 UTC, grafixeyehero approved these changes

2023-10-04 06:11 UTC, merged