Add tv show view
jellyfin/jellyfin-web pull request #4877
Opened 2023-10-13 23:14 UTC by grafixeyehero

2023-10-20 05:56 UTC, thornbill requested changes

2023-10-20 05:56 UTC, thornbill commented on src/apps/experimental/routes/shows/UpComingView.tsx
> +const UpComingView: FC<LibraryViewProps> = ({ parentId }) => {
```suggestion
const UpcomingView: FC<LibraryViewProps> = ({ parentId }) => {
```

2023-10-20 05:56 UTC, thornbill commented on src/hooks/useFetchItems.ts
> +function gropsUpcomingEpisodes(items: BaseItemDto[]) {
```suggestion
function groupsUpcomingEpisodes(items: BaseItemDto[]) {
```

2023-10-20 16:28 UTC, grafixeyehero commented
@thornbill sorry for I force-pushed the commits. 😥

2023-10-20 18:25 UTC, grafixeyehero commented on src/hooks/useFetchItems.ts
> +function gropsUpcomingEpisodes(items: BaseItemDto[]) {
my bad!

2023-10-28 05:43 UTC, thornbill approved these changes

2023-10-28 05:43 UTC, merged