Convert list & card view to react.
jellyfin/jellyfin-web pull request #5166
Opened 2024-01-26 19:31 UTC by grafixeyehero

This PR converts the existing card builder and list view to React.

**Changes**
* Add shared `ItemDto`  Type
* Add Card component
* Add List component
* Reduce cognitive complexity for Primary media info and Text lines

**TODO**
* [ ] Add Refresh Indicator
* [ ] Reduce cognitive complexity for getCardImageUrl
* [ ] Pass class name option for Progress Bar & Auto Time Progress Bar
* [ ] Fix Favorite and Played state for section view

if I miss something or improvement let me know

2024-02-28 16:03 UTC, thornbill requested changes
:sweat_smile: This PR is a beast... very impressive that you were able to replicate the full functionality of the current cards in one go. I think most of my feedback can be boiled down to:

1. Use type imports whenever possible (mostly noticed this for the `FC` import.
2. Use enums for any values possible (`CardShape`, `BaseItemKind`, etc.)
3. I think for at least some of the disabled eslint warnings about unnecessary fragments, the fragment could actually just be removed?
4. I don't think `escapeHTML` will generally be needed in the react components since afaik it automatically escapes everything not using the "dangerous" method.

2024-02-28 22:06 UTC, grafixeyehero commented on src/types/dataAttributes.ts
> +    parentId?: NullableString,
The optional `?` modifier used in `AttributesOpts` is appropriate if these properties are truly optional

2024-02-28 23:23 UTC, grafixeyehero commented on src/components/cardbuilder/Card/Cards.tsx
> +        <>
React `FC` type doesn't like it.

2024-03-07 07:27 UTC, thornbill approved these changes

2024-03-07 13:08 UTC, merged