Re-order Cast & Crew to appear beneath features of the main item
jellyfin/jellyfin-web pull request #5211
Opened 2024-02-18 19:24 UTC by danbracey

**Changes**
When viewing an item in Jellyfin, the Cast & Crew details (including Guest Cast) are less important than the featurettes / extras. This PR simply moves the cast & crew section to the bottom of the details page. This ensures that if users are looking for extras and they can't find it in seasons, there is an affordance given to users scanning the page that they will find the extras next.

2024-04-05 18:49 UTC, nielsvanvelzen approved these changes

2024-04-27 18:18 UTC, 1hitsong commented
Confirmed, this PR changes the order so Special Features appears above the Cast and Crew rows.

However, this also reorders the rows and puts Guest Stars over the Cast row. That order feels off, going Cast & Crew then Guest Stars feels like the correct order, at least to me.

![image](https://github.com/jellyfin/jellyfin-web/assets/3330318/0db9dfe7-a165-4b45-8de6-f043c8914e54)

2024-04-27 18:29 UTC, thornbill commented
We should review the order of sections on this page with Erik before making changes.

2024-04-27 18:30 UTC, Gauvino requested changes

2024-04-27 18:30 UTC, Gauvino commented on src/controllers/itemDetails/index.html
> +
```suggestion
                <div id="castCollapsible" class="verticalSection detailVerticalSection hide">
                    <h2 id="peopleHeader" class="sectionTitle sectionTitle-cards padded-right">${HeaderCastAndCrew}</h2>
                    <div is="emby-scroller" class="padded-top-focusscale padded-bottom-focusscale" data-centerfocus="true">
                        <div id="castContent" is="emby-itemscontainer" class="scrollSlider focuscontainer-x itemsContainer"></div>
                    </div>
                </div>
                
                <div id="guestCastCollapsible" class="verticalSection detailVerticalSection hide">
                    <h2 id="guestCastHeader" class="sectionTitle sectionTitle-cards padded-right">${HeaderGuestCast}</h2>
                    <div is="emby-scroller" class="padded-top-focusscale padded-bottom-focusscale" data-centerfocus="true">
                        <div id="guestCastContent" is="emby-itemscontainer" class="scrollSlider focuscontainer-x itemsContainer"></div>
                    </div>
                </div>       
```

2024-04-27 18:30 UTC, Gauvino commented on src/controllers/itemDetails/index.html
> +
To change the order and show cast & crew before guest

2024-05-08 18:16 UTC, thornbill commented
@danbracey If you could provide a list of all the sections on the details screen before and after this change, it would make it easier to run the change by our UI/UX lead :purple_heart:

2024-08-17 05:34 UTC, GSDan commented
Any updates on this being merged? I'd personally much prefer the Special Features to be in the new proposed position

2024-08-17 06:37 UTC, thornbill commented
Not yet. There has been no response to my request above.

2024-08-18 12:08 UTC, GSDan commented
Not sure if this is any help, but looking at the code, the merge would not change which sections are displayed - just the order they would be in.

Note that the lyrics section was added after the pull request was made

Before:

1.  Primary content (title, video/audio selection, blurb, etc)
2. Schedule
3. Next up
4. Program Guide
5. Children (e.g. seasons in a show)
6. Additional parts
7. More from season
8. Lyrics (added after this request)
9. More from artist
10.  Cast and Crew <-----------
11. Guest stars <-----------
12. Series schedule
13. Special features <-----------
14. Music videos
15. Scenes
16. More like this

After:

1.  Primary content (title, video/audio selection, blurb, etc)
2. Schedule
3. Next up
4. Program Guide
5. Children (e.g. seasons in a show)
6. Additional parts
7. More from season
8. More from artist
9. Series schedule
10. Special features <-----------
11. Music videos
12. Scenes
13. Guest stars <-----------
14. Cast and Crew <-----------
15. More like this

2025-01-13 21:02 UTC, vardogor commented
Bump? Was GSDan's comment not what was needed?

2025-04-01 20:45 UTC, thornbill commented
At the time this PR was created, we did not really have mocks available for the redesigned item details screen.  Reviewing the mocks now this does not match the planned order. Sorry for the delay!

2025-04-01 20:45 UTC, closed without merging