make a React/TypeScript version of emby-checkbox
jellyfin/jellyfin-web pull request #5213
Opened 2024-02-19 07:09 UTC by terite

`CheckBoxElement`  was a wrapper around `emby-checkbox` which worked by having React create the custom component via `dangerouslySetInnerHTML`. This has a fair amount of quirks, quickly becomes less than typesafe, results in components that are difficult to attach event listeners to, and among other things.

Instead of wrapping the custom emby components, let's create idiomatic react versions of them.
* They *react* better to updates.
* No more having to escape html.
* Want data attributes? Just set them directly.
* Supports both controlled and uncontrolled components.

2024-02-23 16:29 UTC, grafixeyehero requested changes

2024-02-23 16:29 UTC, grafixeyehero commented on src/elements/emby-checkbox/Checkbox.tsx
> +            <input className={classNames('emby-checkbox', className)} type='checkbox' {...inputProps } />
```suggestion
            <input ref={inputRef} className={classNames('emby-checkbox', className)} type='checkbox' {...inputProps } />
```

2024-02-23 16:29 UTC, grafixeyehero commented on src/apps/dashboard/routes/users/access.tsx
> +        title += ' ' + appName;
```suggestion
        title += ' - ' + appName;
```

2024-02-23 17:11 UTC, grafixeyehero commented on src/elements/emby-checkbox/Checkbox.tsx
> +    const elem = this.parentNode as HTMLSpanElement;
```suggestion
    const elem = this.parentNode as HTMLLabelElement;
```

2024-02-25 01:37 UTC, grafixeyehero approved these changes

2024-02-26 15:09 UTC, thornbill requested changes

2024-02-26 15:09 UTC, thornbill commented on src/elements/emby-checkbox/Checkbox.tsx
> +interface Props {
```suggestion
interface CheckboxProps {
```

2024-12-10 10:02 UTC, closed without merging