fix: move mjpeg acceleration option into trickplay panel
jellyfin/jellyfin-web pull request #5331
Opened 2024-03-27 05:14 UTC by gnattu

**Changes**

This is a followup of #5326. This option is very trickplay specific and should not belongs to general encoding options. This PR moves the option into the trickplay panel and changed the option texts to be more specific and less confusing.

**Issues**
This change is related to jellyfin/jellyfin#11229

Fixes #5363

2024-03-27 07:00 UTC, nyanmisaka approved these changes

2024-03-27 11:29 UTC, gnattu commented on src/strings/en-us.json
> +    "LabelTrickplayAccelEncodingHelp": "Currently only available on QSV and VAAPI, this option has no effect on other hardware acceleration methods.",
Then modify the text in the future. 

VideoToolbox also provides MJPEG encoder but it is not implemented in ffmpeg.

MJPEG in this small size should not be a too big problem for modern CPUs anyway.

2024-03-29 07:45 UTC, thornbill requested changes
The `LinkTrickplayAcceleration` file and any related translations should be removed also.

2024-03-29 07:53 UTC, gnattu commented
> The `LinkTrickplayAcceleration` file and any related translations should be removed also.

Done

2024-03-29 17:34 UTC, thornbill reviewed
Only the en-us translation file should be modified. Weblate handles the rest.

2024-03-30 00:12 UTC, gnattu commented
> Only the en-us translation file should be modified. Weblate handles the rest.

Done. The one in en-US was already removed before your comments so I thought it was needed to cleanup the leftovers in other languages as well.

2024-04-14 11:32 UTC, nielsvanvelzen approved these changes

2024-04-20 06:54 UTC, thornbill approved these changes

2024-04-20 06:54 UTC, merged