Don’t bind to keyevents of media keys
jellyfin/jellyfin-web pull request #5526
Opened 2024-05-17 08:10 UTC by gnattu

These events are already handled by MediaSession. On some operating systems, like Windows, the browser will send both the MediaSession event and the keydown event to the webpage, causing the event to be handled twice and resulting in issues.

**Changes**

Remove media key binding in keyboardNavigation

**Issues**

Fixes #5523

2024-05-17 09:03 UTC, dmitrylyzo commented
This needs to be tested on TV with keyboard connected. `keyboardNavigation.js` is primarily for TV.

2024-05-17 09:43 UTC, dmitrylyzo commented
We could do something like this:
```js
const hasMediaSession = 'mediaSession' in navigator;

...

case 'MediaPlayPause':
    if (!hasMediaSession) inputManager.handleCommand('playpause');
    break;
```
But I have no idea if modern TVs have `MediaSession`.

2024-05-17 09:46 UTC, gnattu commented
> But I have no idea if modern TVs have MediaSession.

Even if they do, is it really reliable is also questionable.

Do we have the double event issue for TV yet? If we don't then probably one of the event handler is not really working for the TVs, but which one is unknown.

2024-05-17 10:23 UTC, dmitrylyzo commented
I'm sure `keydown` works for `Media*` keys on Tizen - that's how Samsung recommends handling them.
https://developer.samsung.com/smarttv/develop/api-references/tizen-web-device-api-references/tvinputdevice-api.html
```js
var i, keyCode = {}, supportedKeys;
supportedKeys = tizen.tvinputdevice.getSupportedKeys();
for (i = 0; i < supportedKeys.length; i++) {
    keyCode[supportedKeys[i].name] = supportedKeys[i].code;
}
if(keyCode.hasOwnProperty("ChannelUp")) {
    tizen.tvinputdevice.registerKey("ChannelUp");
}
window.addEventListener("keydown", function(keyEvent) {
    // identify the key by the numeric code from the keyEvent
    if(keyEvent.keyCode === keyCode.ChannelUp) {
        console.log("The CHANNEL UP was pressed");
    }
});
```

After a quick look, there is no MediaSession API.
https://developer.samsung.com/smarttv/develop/specifications/web-engine-specifications.html

2024-05-19 15:49 UTC, gnattu commented
@GeorgeH005 Can you do me a favor for this as well? Can you test if webOS have MediaSession and is its MediaSession reliable? So that we can have some level of confidence for two major smart TV platforms.

2024-05-21 06:14 UTC, gnattu commented
Updated to make the compatibility better. Now it only binds media keys on TV and browsers not having mediaSession. Should work good enough and cover most use cases.

2024-05-21 07:28 UTC, dmitrylyzo commented on src/scripts/keyboardNavigation.js
> +        if (!layoutManager.tv && isMediaKey(key) && 'mediaSession' in navigator) {
I wonder which is faster, `... in ...` or a const (defined in the beginning of `enable`)? Nanoseconds (maybe a little more on old hardware or TVs), but still.

2024-05-21 10:22 UTC, dmitrylyzo approved these changes

2024-05-21 14:36 UTC, dmitrylyzo requested changes

2024-05-21 14:36 UTC, dmitrylyzo commented on src/scripts/keyboardNavigation.js
> +        if (!layoutManager.tv && isMediaKey(key) && hasMediaSession) {
Overlooked this. We can activate TV layout on the PC. We should test the browser "type".
```suggestion
        if (!browser.tv && isMediaKey(key) && hasMediaSession) {
```

2024-05-21 14:54 UTC, dmitrylyzo approved these changes

2024-05-21 20:38 UTC, merged