Add possibility to display detailLogo on TV with CSS customization
jellyfin/jellyfin-web pull request #5620
Opened 2024-05-28 18:53 UTC by vdubuisson

**Changes**

Add the possibility to display the detailLogo on TV with CSS customization.
If you don't customize your CSS, you won't see any difference and the detailLogo will still be hidden.

2024-06-09 05:45 UTC, thornbill approved these changes

2024-06-09 05:47 UTC, thornbill requested changes

2024-06-09 05:47 UTC, thornbill commented on src/styles/librarybrowser.scss
> +.layout-mobile, .layout-tv {
```suggestion
.layout-mobile,
.layout-tv {
```

2024-07-26 15:28 UTC, merged

2024-07-26 17:38 UTC, tedhinklater commented
woo!