Fix download all for Safari
jellyfin/jellyfin-web pull request #5744
Opened 2024-06-30 01:38 UTC by jchuong

**Changes**

Added check to use fallback downloader for iOS
Added check for safari to use the delayed download function
Remove old comment about firefox, as a.click() supported since Firefox 75 (2020) [ref](https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement/click#browser_compatibility)

**Issues**

Fixes #5672

2024-06-30 01:48 UTC, jchuong commented
I've done basic test with 

* Windows Firefox 128.0b9
* MacOS Safari 17.4.1
* iPad Safari 

I have *not* tested:
* Other browsers in iOS (Chrome or Firefox for example)
* iPhone
* Shows that are not on same domain see below
https://github.com/jellyfin/jellyfin-web/blob/c40bf002df05c527126a16e5dde13fe09a83ddb7/src/scripts/multiDownload.js#L30-L35

2024-07-28 22:31 UTC, gnattu requested changes
Can you also rebase this to 10.9 branch as a hotfix?

We may rewrite this to be less hacky in 10.10

2024-07-28 22:31 UTC, gnattu commented on src/scripts/multiDownload.js
> +        if ((browser.firefox && !sameDomain(url))
I'd like to add this delay to all browsers. On browsers that seem to be happy with this will still missing some episodes without the delay.

2024-08-13 03:40 UTC, jchuong commented
Closing to rebase on 10.9

2024-08-13 03:40 UTC, closed without merging