Redesign add plugins page
jellyfin/jellyfin-web pull request #5773
Opened 2024-07-11 20:34 UTC by thornbill

**Changes**
Implements a completely overhauled plugin installation page.

![Screenshot 2024-07-11 at 16-27-50 Jellyfin](https://github.com/jellyfin/jellyfin-web/assets/3450688/01cd6fbe-17eb-4a46-abe4-ed2d5689b502)

![Screenshot 2024-07-11 at 16-29-44 Jellyfin](https://github.com/jellyfin/jellyfin-web/assets/3450688/f0c02335-4990-42e8-b89a-48b7af7a12a6)

Additional features that could be added in the future:

* Restart button when the plugin status is restart needed
* Indicator when a plugin update is available

**Issues**
N/A

2024-07-12 19:11 UTC, thornbill commented
Not sure why the preview link comment is not being posted, but you can find it here for testing:

Action run: https://github.com/jellyfin/jellyfin-web/actions/runs/9911940022
CF Pages url: https://ad315c5f.jellyfin-web.pages.dev/

2024-07-12 19:47 UTC, nielsvanvelzen commented
Did some testing on the CF deployment. The design looks great and it's a real improvement from the current page, Here are my findings. Some are nitpicks, other are most likely due to how the API works.

- I added my own server so I could sign in as an admin user. After refreshing the page it went back to the default (unstable demo). Unrelated to this issue but probably needs some attention.
- A plugin with extra pages (Like the playback reporting plugin) should probably have those pages added as buttons, just like the "settings" button.
- Pressing the "install" button doesn't give any feedback until the install is completed. Considering this task may take some time it would be nice to show a progress indicator or something like that
- Pressing the "install" button should _probably_ show a confirmation dialog first (like uninstall)
- When I install a plugin and then uninstall it again it still shows the "The plugin has been successfully installed." message
- The "The plugin has been successfully installed." message could probably have a "restart" button on the right side
- The install buttons in the revision history should be renamed to "downgrade" when there is a newer version installed, with a dialog to confirm
- When the plugin is auto-updated but still needs a restart, the status is "restart". Could use a restart button to make it easier (maybe add an message just like when the plugin is installed).
- We should probably open this page when clicking on a plugin from the "My Plugins" page

2024-07-12 20:56 UTC, thornbill commented
- I added my own server so I could sign in as an admin user. After refreshing the page it went back to the default (unstable demo). Unrelated to this issue but probably needs some attention.
  - Likely part of larger issue with our multi-server handling.
- A plugin with extra pages (Like the playback reporting plugin) should probably have those pages added as buttons, just like the "settings" button.
  - Probably not currently possible. Plugins seem to also use configuration pages to expose static assets (js files) and don't assign the different pages unique display names.
- Pressing the "install" button doesn't give any feedback until the install is completed. Considering this task may take some time it would be nice to show a progress indicator or something like that
  - I was planning to use the MUI [LoadingButton](https://mui.com/material-ui/react-button/#loading-button) for this but it requires installing their "labs" package so I was going to do it in a separate PR.
- Pressing the "install" button should _probably_ show a confirmation dialog first (like uninstall)
  - This keeps the current behavior. A confirmation/warning prompt is displayed if installing from a third-party repository.
- When I install a plugin and then uninstall it again it still shows the "The plugin has been successfully installed." message
  - They use different APIs so it doesn't reset automatically, but should be an easy fix.
- The "The plugin has been successfully installed." message could probably have a "restart" button on the right side
  - Planned for a future PR
- The install buttons in the revision history should be renamed to "downgrade" when there is a newer version installed, with a dialog to confirm
  - Seems like a good enhancement for a future PR... We would need to pull in a dependency or write a utility to compare versions.
- When the plugin is auto-updated but still needs a restart, the status is "restart". Could use a restart button to make it easier (maybe add an message just like when the plugin is installed).
  - Planned for a future PR
- We should probably open this page when clicking on a plugin from the "My Plugins" page
  - Planned for a future PR (the page doesn't handle built-in plugins great atm)

2024-07-14 19:33 UTC, grafixeyehero requested changes

2024-07-14 19:33 UTC, grafixeyehero commented on src/apps/dashboard/routes/plugins/plugin.tsx
> +    }, [ isConfigurationPagesLoading, isPackageInfoLoading, isPluginsLoading ]);
```suggestion
    const isLoading =
        isConfigurationPagesLoading || isPackageInfoLoading || isPluginsLoading;
```

2024-07-14 19:33 UTC, grafixeyehero commented on src/apps/dashboard/routes/plugins/plugin.tsx
> +    }, [ searchParams ]);
```suggestion
    const pluginName = searchParams.get('name') ?? undefined;
```

2024-07-14 19:33 UTC, grafixeyehero commented on src/apps/dashboard/routes/plugins/plugin.tsx
> +    }, [ api, configurationPages, isEnabledOverride, isPluginsLoading, pluginId, packageInfo, pluginName, plugins ]);
```suggestion
    const pluginDetails = useMemo(() => {
        if (pluginId && !isPluginsLoading) {
            const pluginInfo = findBestPluginInfo(pluginId, plugins);

            let version;
            if (pluginInfo) {
                // Find the installed version
                const repoVersion = packageInfo?.versions?.find(v => v.version === pluginInfo.Version);
                version = repoVersion || {
                    version: pluginInfo.Version,
                    VersionNumber: pluginInfo.Version
                };
            } else {
                // Use the latest version
                version = packageInfo?.versions?.[0];
            }

            let imageUrl;
            if (pluginInfo?.HasImage) {
                imageUrl = api?.axiosInstance.getUri({
                    baseURL: api.basePath,
                    url: `/Plugins/${pluginInfo.Id}/${pluginInfo.Version}/Image`
                });
            }

            return {
                canUninstall: !!pluginInfo?.CanUninstall,
                description: pluginInfo?.Description || packageInfo?.description || packageInfo?.overview,
                id: pluginId,
                imageUrl: imageUrl || packageInfo?.imageUrl || undefined,
                isEnabled: (isEnabledOverride && pluginInfo?.Status === PluginStatus.Restart)
                    ?? pluginInfo?.Status !== PluginStatus.Disabled,
                name: pluginName || pluginInfo?.Name || packageInfo?.name,
                owner: packageInfo?.owner,
                status: pluginInfo?.Status,
                configurationPage: findBestConfigurationPage(configurationPages || [], pluginId),
                version,
                versions: packageInfo?.versions || []
            };
        }
    }, [api?.axiosInstance, api?.basePath, configurationPages, isEnabledOverride, isPluginsLoading, packageInfo?.description, packageInfo?.imageUrl, packageInfo?.name, packageInfo?.overview, packageInfo?.owner, packageInfo?.versions, pluginId, pluginName, plugins]);
```

2024-07-14 19:35 UTC, grafixeyehero commented on src/apps/dashboard/routes/plugins/plugin.tsx
> +    }, [ api, configurationPages, isEnabledOverride, isPluginsLoading, pluginId, packageInfo, pluginName, plugins ]);
move the pluginDetails change to line 85
this change reduces unnecessary re-renders.

Before:
![Screenshot 2024-07-14 214731](https://github.com/user-attachments/assets/6eca4220-e4f5-443b-b197-751a7a0e33ac)

After:
![Screenshot 2024-07-14 213816](https://github.com/user-attachments/assets/b6499a0f-11cd-48a9-baa3-7869b0b4649c)

2024-07-14 19:51 UTC, grafixeyehero commented
left those change to the top.
Those change reduces unnecessary re-renders
Before:
![Screenshot 2024-07-14 214731](https://github.com/user-attachments/assets/25c19a2a-f50c-4474-b0d4-e3febc19a4e3)

After:
![Screenshot 2024-07-14 213816](https://github.com/user-attachments/assets/47fcbb97-585a-423b-809d-4db3019c42d5)

2024-07-15 22:03 UTC, grafixeyehero requested changes

2024-07-19 16:14 UTC, grafixeyehero approved these changes

2024-07-26 23:34 UTC, thornbill commented
The version list expands when you click on a version to show the change log and an install button.

2024-07-26 23:34 UTC, merged