Enable software tonemappin options
jellyfin/jellyfin-web pull request #5784
Opened 2024-07-14 10:00 UTC by gnattu

This enables the tonemapping options for pure software transcoding pipeline. The software implementation currently has less feature than the hardware ones so the help text is also modified for it. Notably:

- The tonemapping mode is always MAX
- Does not support Dolby Vision reshaping

**Changes**

**Issues**

2024-08-21 17:56 UTC, thornbill requested changes

2024-08-21 17:56 UTC, thornbill commented on src/controllers/dashboard/encodingsettings.js
> +        if (this.value === '' || this.value === 'amf' || this.value === 'nvenc' || this.value === 'qsv' || this.value === 'vaapi' || this.value === 'rkmpp' || this.value === 'videotoolbox') {
```suggestion
        const isHwaSelected = [ 'amf', 'nvenc', 'qsv', 'vaapi', 'rkmpp', 'videotoolbox' ].includes(this.value);
        if (this.value === '' || isHwaSelected) {
```

2024-08-21 17:56 UTC, thornbill commented on src/controllers/dashboard/encodingsettings.js
> +        if (this.value === 'amf' || this.value === 'nvenc' || this.value === 'qsv' || this.value === 'vaapi' || this.value === 'rkmpp' || this.value === 'videotoolbox') {
```suggestion
        if (isHwaSelected) {
```

2024-08-21 21:30 UTC, thornbill commented on src/controllers/dashboard/encodingsettings.html
> +                        <div class="fieldDescription checkboxFieldDescription AllowTonemappingSoftwareHelp">${AllowTonemappingSoftwareHelp}</div>
Good catch! That would be preferred.

2024-08-22 12:54 UTC, dmitrylyzo commented on src/controllers/dashboard/encodingsettings.js
> +        // }
no comments

2024-08-22 14:53 UTC, dmitrylyzo approved these changes

2024-08-23 18:30 UTC, thornbill approved these changes

2024-08-23 18:30 UTC, merged