Add Firefox 121+ to list of HEVC-supporting browsers
jellyfin/jellyfin-web pull request #5876
Opened 2024-08-05 02:34 UTC by fanonwue

Mozilla implemented support for HEVC decoding using WMF on Windows. Support for HEVC playback is being tested anyway using the canPlayHevc() function, so this should be a safe change for other operating systems (or systems without hardware HEVC decoding) as well.

**Changes**
Firefox (121 and later) supports HEVC decode in fMP4 containers when it's using the new WMF-based media backend, so it should be added to the conditional check for that. The new backend is only available on Windows and not enabled by default (iirc), but when it's present, decoding works perfectly. The canPlayHevc() function correctly reports decoding capabilities, so a fallback to H264 happens when `media.wmf.hevc.enabled` is disabled, WMF is not present or no hardware decoding is available (I was only able to test this using WSL2 so far, but I doubt that this is going to be different for "real" systems).

**Issues**
Fixes #5706

2024-08-11 18:37 UTC, gnattu commented
Firefox does not support 10bit HEVC and is lying with the feature tests. The playback will automatically fallback to transcoding with our fail and retry mechanism, but I think it is better to add check here:

https://github.com/jellyfin/jellyfin-web/blob/9fe96669370e4616dec6b4420f0aa7816cec8c8f/src/scripts/browserDeviceProfile.js#L964-L983

Basically we should skip these main10 profile tests for Firefox so that they are not mistakenly marked as supported to avoid unnecessary retry and reduce video load time.

2024-08-14 15:21 UTC, fanonwue commented
Nothing can ever be easy, huh?
Sorry about that, I don't have any HDR capable display so I can't really test it I think.

So basically if the browser is Firefox, we should only add `main` and not `main 10` to the profiles, right?

2024-08-14 15:49 UTC, fanonwue commented
I have added an override for Firefox's real capabilities at the end of the block of checks that determine HEVC profile compatibility.
https://github.com/jellyfin/jellyfin-web/blob/dac35a1d4b1d7a87a9bb0231742be035fa4d8a33/src/scripts/browserDeviceProfile.js#L983-L987

2024-08-29 14:50 UTC, fanonwue commented
Hi,

I understand that you are probably quite busy. But I wanted to ask whether anyone from the JF team thinks we can proceed with adding this? Is there something else I could do?

2024-08-29 18:34 UTC, gnattu commented
Please be patient as the web team is super busy. It is normal that a PR is not merged for weeks as lots of mine are in this state as well. I'm good with your current solution but we still need the web team members to look at it.

2024-09-01 20:03 UTC, kam821 commented
1) It may be a good idea to restrict HEVC to Windows only by adding check:
(browser.firefox && browser.versionMajor >= 121 && browser.windows)
2) Bugs I've noticed so far - on one HEVC-encoded video, a horizontal, green line is displayed at the bottom of the video content.
So far, this problem only affects one video (series). Once, randomly I managed to play that title without that line appearing, but generally this line is almost always displayed.

Green line:
![obraz](https://github.com/user-attachments/assets/724d02b4-01d3-4fc1-8cf2-1d110e62456e)

Encoding parameters of problematic video:
![obraz](https://github.com/user-attachments/assets/babdbb26-d972-42d5-8dc5-5346d947f687)

2024-09-01 23:07 UTC, gnattu commented
> It may be a good idea to further restrict HEVC to Windows only by adding appropriate check:

Firefox on other platforms do not report HEVC as supported so this is currently redundant

> Bugs I've noticed so far - on one HEVC-encoded video, a horizontal, green line is displayed at the bottom of the video content.

We can do little if it is a firefox bug

2024-09-02 20:04 UTC, nyanmisaka commented
> > We can do little if it is a firefox bug
> 
> This may not necessarily be a problem with Firefox itself. I found some links that describe same/similar problem that has been fixed in the past. [jellyfin/jellyfin#2292](https://github.com/jellyfin/jellyfin/issues/2292) [jellyfin/jellyfin#3021](https://github.com/jellyfin/jellyfin/issues/3021) [jellyfin/jellyfin#5535](https://github.com/jellyfin/jellyfin/issues/5535)

One is an AMD driver issue and the other two are a QSV filter issue I handled in the past. They are not related to this one because there is no hardware transcoding involved. If Chrome doesn't have this problem on the same file, then you need to wait for Firefox to fix their frame cropping.

2024-09-22 13:47 UTC, GodTamIt commented
> Firefox does not support 10bit HEVC and is lying with the feature tests.

@gnattu Which feature tests/under which conditions is Firefox lying? I recently filed [a related bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1915307) and may look into upstreaming a fix for it so might be useful to collect all issues into a fix.

This link might be helpful: https://cconcolato.github.io/media-mime-support

2024-09-22 14:12 UTC, gnattu commented
> Which feature tests/under which conditions is Firefox lying? 

Firefox reports HEVC main10 has supported for [`canPlayType()`](https://developer.mozilla.org/en-US/docs/Web/API/HTMLMediaElement/canPlayType) method but it actually does not, see code quoted [here](https://github.com/jellyfin/jellyfin-web/pull/5876#issuecomment-2282850106) for the real test.

2024-10-30 07:23 UTC, nyanmisaka commented
@fanonwue Just tested Firefox 132 stable with `media.wmf.hevc.enabled == 1` and found that HEVC Main 10 playback has been fixed in this version. Client-side HDR tonemapping is still not supported. But I think this PR can go ahead.

![firefox132](https://github.com/user-attachments/assets/3ebeff7d-f91e-473d-a0cc-05acd4bfdd8c)

2024-10-30 11:35 UTC, fanonwue commented
> @fanonwue Just tested Firefox 132 stable with `media.wmf.hevc.enabled == 1` and found that HEVC Main 10 playback has been fixed in this version. Client-side HDR tonemapping is still not supported. But I think this PR can go ahead.
> 
> ![firefox132](https://github.com/user-attachments/assets/3ebeff7d-f91e-473d-a0cc-05acd4bfdd8c)
> 

In that case, do you want me to adjust the workaround to only work below 132?

2024-10-30 14:57 UTC, nyanmisaka commented
> In that case, do you want me to adjust the workaround to only work below 132?

Since HEVC is experimental in older versions, I don't think it's necessary to add a workaround specifically for those broken versions, as browser updates are usually frequent.

2024-10-30 17:24 UTC, nyanmisaka commented
> Sorry, this is my first time contributing to a larger project: Do you want me to revert the last commit that introduced the override then? I think it would be good to update the minimum FF version to 132 then as well, I've set it to 121 in the original commit.

It should be enough to bump the checked version up to 132. 
All that's left is for the user to manually enable the experimental flag in Firefox.

2024-10-31 21:27 UTC, fanonwue commented
> It should be enough to bump the checked version up to 132.

I've removed the previous override (disallowing HEVC main10) and raised the minimum version to 132.

2024-11-06 23:05 UTC, fanonwue commented
> We have more problems regarding this because Firefox 132 on Windows is lying again where it will report HEVC as supported even that flag is disabled as long as the media codec extension is installed which is super annoying

Just tested it with Firefox Nightly 134 and this does not happen. My test video is HEVC main10, it's streaming directly when setting `media.wmf.hevc.enabled` to 1. But when you set it back to 0 (and restart the browser), it gets transcoded to H264 again.

2025-01-10 07:35 UTC, gnattu requested changes
Bump the version to 134 where the HEVC support is official and do not require a feature flag. We should be ready to go with this PR.

2025-01-10 07:35 UTC, gnattu commented on src/scripts/browserDeviceProfile.js
> +        && (browser.edgeChromium || browser.safari || browser.tizen || browser.web0s || (browser.chrome && (!browser.android || browser.versionMajor >= 105)) || (browser.opera && !browser.mobile) ||
```suggestion
        && (browser.edgeChromium || browser.safari || browser.tizen || browser.web0s || (browser.chrome && (!browser.android || browser.versionMajor >= 105)) || (browser.opera && !browser.mobile) || (browser.firefox && browser.versionMajor >= 134))) {
```

2025-01-11 01:33 UTC, gnattu approved these changes

2025-02-05 03:20 UTC, wbsdty331 commented
Firefox 136 brings [hardware-accelerated HEVC playback](https://www.mozilla.org/en-US/firefox/136.0beta/releasenotes/)  to macOS.

should we need to raise minimum version to 136+?

2025-02-06 18:43 UTC, fanonwue commented
I would assume Firefox reports it's playback capabilities correctly, meaning it wouldn't report being compatible with any HEVC stuff on Mac. But I don't use Apple devices so I can't test that.

2025-02-13 17:56 UTC, thornbill approved these changes

2025-02-13 17:57 UTC, merged