Add OriginalLanguage as option to PreferredAudioLanguage
jellyfin/jellyfin-web pull request #6022
Opened 2024-09-04 18:35 UTC by Lampan-git

**Changes**
Add OriginalLanguage as option to PreferredAudioLanguage to enable: https://github.com/jellyfin/jellyfin/pull/12579

2024-09-07 13:15 UTC, dmitrylyzo commented on src/strings/en-gb.json
> +    "OriginalLanguage": "Original Language",
Undo the changes in the `en-gb.json` file. They must be made via Weblate. Otherwise it may cause merge conflicts.

2024-09-07 13:15 UTC, dmitrylyzo commented on src/strings/sv.json
> +    "LabelOriginalLanguage": "Originalspråk",
Undo the changes in the `sv.json` file. They must be made via Weblate. Otherwise it may cause merge conflicts.

2024-09-07 13:49 UTC, dmitrylyzo commented on src/components/metadataEditor/metadataEditor.js
> +        context.querySelector('#txtOriginalLanguage').label(globalize.translate('LabelOriginalName'));
```suggestion
        context.querySelector('#txtOriginalLanguage').label(globalize.translate('LabelOriginalLanguage'));
```

2024-09-07 14:01 UTC, Lampan-git commented on src/components/metadataEditor/metadataEditor.js
> +        context.querySelector('#txtOriginalLanguage').label(globalize.translate('LabelOriginalName'));
No, that's my bad, I removed that line.

2026-05-07 18:48 UTC, shindouj commented
@thornbill @crobibero @nielsvanvelzen Since the backend PR (https://github.com/jellyfin/jellyfin/pull/12579) has been merged, perhaps this could get some attention as well? :)

2026-05-07 19:44 UTC, thornbill commented
Do **NOT** ping random people. Maintainers will be notified according to **their** GH preferences when you just leave a comment.

2026-05-07 19:46 UTC, shindouj commented
I have pinged the latest reviewers in the project, not people at random. Please bear with me, it took a year to get any attention to the backend PR at all.

2026-05-07 20:34 UTC, thornbill commented
2/3 people you pinged do not regularly review PRs here, so yes that is random, intrusive, and incredibly inconsiderate.

2026-05-07 20:51 UTC, shindouj commented
My apologies. That was not my intention. I will cease the off-topic on that.

2026-05-19 19:30 UTC, MBR-0001 commented
I'm assuming this is related to this user setting
<img width="1077" height="1089" alt="image" src="https://github.com/user-attachments/assets/c019372f-cb69-444d-affa-bfdd14a67c2c" />

if so, shouldn't the input field in the metadata editor also be a dropdown?
<img width="374" height="362" alt="image" src="https://github.com/user-attachments/assets/e4928692-6a06-45aa-be13-9447c29fc4ec" />

2026-05-19 20:07 UTC, Lampan-git commented
> shouldn't the input field in the metadata editor also be a dropdown?

Yes, that does make a lot of sense. I have changed it.

2026-05-19 20:26 UTC, Lampan-git commented
> I'm assuming this is related to this user setting

I see however that you don't have the choice of "Original Language" in your "Preferred audio language". Is that when you have checked out this PR, because you do have the Original language metadata in the editor which is confusing to me. I don't have any issues of not seeing Original Language in the Audio Settings on my end.

2026-05-20 17:42 UTC, MBR-0001 commented
> > I'm assuming this is related to this user setting
> 
> I see however that you don't have the choice of "Original Language" in your "Preferred audio language". Is that when you have checked out this PR, because you do have the Original language metadata in the editor which is confusing to me. I don't have any issues of not seeing Original Language in the Audio Settings on my end.

Yeah I was comparing to stable, seems I screenshotted the wrong app :)

2026-05-20 18:43 UTC, MBR-0001 requested changes

2026-05-20 18:43 UTC, MBR-0001 commented on src/components/settingshelper.js
> +    html += "<option value='OriginalLanguage'>" + globalize.translate('OriginalLanguage') + '</option>';
This adds the option to the user subtitles configuration page, seems out of scope/unintentional?

<img width="805" height="1132" alt="Image" src="https://github.com/user-attachments/assets/4a7356f7-718d-4de7-8784-15adef4d6037" />

2026-05-20 18:43 UTC, MBR-0001 commented on src/strings/en-us.json
> +    "LabelOriginalLanguage": "Original language",
Noticed two same entries, from what I see this value is used for html labels while the one below is used for actual dropdown values. While I kinda understand the idea it seems a bit redundant, one should be enough?

But I may be wrong, @thornbill what's the rule of thumb for stuff like this?

2026-05-20 18:43 UTC, MBR-0001 commented on src/components/metadataEditor/metadataEditor.template.html
> +                <div id="fldOriginalLanguage" class="selectContainer">
add hide class so it follows other fields that show dynamically (hidden by default)

2026-05-20 19:22 UTC, Lampan-git commented on src/components/settingshelper.js
> +    html += "<option value='OriginalLanguage'>" + globalize.translate('OriginalLanguage') + '</option>';
It was indeed unintentional

2026-05-20 19:23 UTC, Lampan-git commented on src/strings/en-us.json
> +    "LabelOriginalLanguage": "Original language",
I didn't change for now. But I can change if its preferred

2026-05-20 19:59 UTC, MBR-0001 approved these changes
LGTM, I'll leave the label decision to Bill

2026-05-27 14:55 UTC, thornbill requested changes

2026-05-27 14:55 UTC, thornbill commented on src/components/metadataEditor/metadataEditor.js
> +        || item.Type === 'TvChannel') {
This is now inline with the block contents making it harder to read.

2026-05-27 14:55 UTC, thornbill commented on src/strings/en-us.json
> +    "OriginalLanguage": "Original Language",
Let's drop the `LabelOriginalLanguage` and update the casing of this one:

```suggestion
    "OriginalLanguage": "Original language",
```

Please update the casing of `AnyLanguage` to be "Any language" also. Thanks!

2026-05-27 15:01 UTC, Lampan-git commented on src/components/metadataEditor/metadataEditor.js
> +        || item.Type === 'TvChannel') {
I believe this was done by the formatter, but I will revert.

2026-05-29 19:09 UTC, thornbill approved these changes

2026-05-29 19:11 UTC, thornbill commented
This one was a long time coming. Thanks for your patience! :purple_heart:

2026-05-29 19:13 UTC, merged