Only add gain node when normalization enabled
jellyfin/jellyfin-web pull request #6142
Opened 2024-10-01 09:13 UTC by gnattu

Currently, we create a Web Audio session and connect to it regardless of the normalization status, hoping it will work. However, it turns out that some devices exhibit buggy behavior when the Web Audio session is connected to a gain node, causing distorted audio playback. This PR makes that the gain element is only created when normalization is not off. The downside is that users must manually stop the currently playing song and start a new one to apply the state change between on and off. By doing this, users experiencing bugged playback can turn off the normalization so that the playback behavior would be the same as 10.8 which *should* be fine.

We do need this workaround because:

- Device and/or OS vendors are less concerned about this issue than we are, meaning it might take a long time to be fixed upstream.
- Not all devices have the option to update to the latest software. We need to provide users with such devices a workaround so that they can at least have a normal playback, even if it means losing a feature.

**Changes**

- Only create gain element when normalization is not off.

**Issues**

See jellyfin#11614, hopefully will workaround that.

2024-10-01 10:22 UTC, dmitrylyzo commented on src/plugins/htmlAudioPlayer/plugin.js
> +                    addGainElement(elem);
Probably missing from the beginning.
```suggestion
                    addGainElement(elem);
                    if (!self.gainNode) return;
```
`addGainElement` already has an error message.

2024-10-01 10:27 UTC, dmitrylyzo approved these changes

2024-10-02 08:41 UTC, ferferga requested changes
I wanted to comment this yesterday, but wanted to actually verify it, and I can confirm now that this doesn't fix the issue.

The problem start as soon as the AudioContext is connected to the media element, no other nodes are necessary. In Vue for instance, we use WebAudio for analyzing the audio waveform, but we don't apply any gain (or any other node that modifies the output), yet the error still happens.

In order to fix the underlying issue, WebAudio must be completely suspended.

2024-10-02 08:46 UTC, gnattu commented
But what this PR actually does is not to crate the `AudioContext` at all when normalization is off? So it makes me quite confused why that did not fix your problem.

2024-10-02 12:06 UTC, thornbill approved these changes

2024-10-02 12:06 UTC, merged