Fix focus loss on popups in Samsung Tizen 8 Smart TVs
jellyfin/jellyfin-web pull request #6408
Opened 2024-12-24 19:28 UTC by dantesbr

The web client loses focus when a popup is displayed on Samsung Smart TVs with Tizen 8 (OneUI/Tizen 8). This issue only occurs on the TV itself and not on the Tizen emulator.
Fixes the issue https://github.com/jellyfin/jellyfin-tizen/issues/311

**Changes**  
This PR updates `confirm.js` to ensure that the native `window.confirm` is not used on Samsung Smart TVs with Tizen 8 (OneUI). Instead, it uses a custom confirmation dialog to prevent focus-related issues specific to this platform.  

**Issues**  
Fixes https://github.com/jellyfin/jellyfin-tizen/issues/311

2024-12-29 20:50 UTC, thornbill requested changes

2024-12-29 20:50 UTC, thornbill commented on src/components/confirm/confirm.js
> +    if (browser.tizenVersion && browser.tizenVersion >= 8) {
The should be integrated with the Tizen check below

2024-12-31 15:01 UTC, morpheus133 commented
I think same modification is needed in also here:
https://github.com/jellyfin/jellyfin-web/blob/5b4cfbf4103c939b59c316a262a7a60fc8d7759b/src/components/alert.js#L6-L14

2025-01-05 00:21 UTC, dmitrylyzo commented on src/components/alert.js
>          && !(browser.tizenVersion && browser.tizenVersion < 3)
```suggestion
        !browser.web0s
        && !(browser.tizenVersion && (browser.tizenVersion < 3 || browser.tizenVersion >= 8))
```
Technically, we can omit `browser.tizenVersion` and just do `!(browser.tizenVersion < 3 || browser.tizenVersion >= 8)`.

2025-01-05 00:21 UTC, dmitrylyzo commented on src/components/confirm/confirm.js
>          && !(browser.tizenVersion && browser.tizenVersion < 3)
```suggestion
        && !(browser.tizenVersion && (browser.tizenVersion < 3 || browser.tizenVersion >= 8))
```

2025-01-06 21:58 UTC, morpheus133 commented on src/components/confirm/confirm.js
>          && !(browser.tizenVersion && browser.tizenVersion < 3)
Can I have a question:
Why do we use NativeAlert at all?

With this modification we wont use it before 4 and after 8. 
And most probably nobody will check it  after 8.X that the function is corrected by Samsung so it will remain there forever.
Simple we can use this: `&& !(browser.tizenVersion)` and all version will be the same.

2025-01-06 22:06 UTC, dmitrylyzo commented on src/components/confirm/confirm.js
>          && !(browser.tizenVersion && browser.tizenVersion < 3)
> Why do we use NativeAlert at all?

Tbh, I ask the same question myself. 😅
It is inherited from Emby. 🤷‍♂️

> Simple we can use this: `&& !(browser.tizenVersion)` and all version will be the same.

`!browser.tizen` is shorter.

2025-01-09 19:38 UTC, dmitrylyzo approved these changes
LGTM.
But really, do we need native modals (https://github.com/jellyfin/jellyfin-web/pull/6408#discussion_r1904679775)?

Bill, don't forget to squash commits :sweat_smile:

2025-01-10 01:31 UTC, thornbill commented
I have no clue if they are needed... I wouldn't remove them in a backport but seems like a good thing to add to the queue for 10.11. 🙂

2025-01-10 01:32 UTC, thornbill approved these changes

2025-01-10 01:32 UTC, merged